// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Assignmet_EF_D01.Models;

public partial class audit
{
    public string name { get; set; }

    public DateOnly? date { get; set; }

    public int? id { get; set; }

    public int? oldsal { get; set; }

    public int? newsal { get; set; }
}