// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Assignmet_EF_D01.Models;

public partial class customer
{
    public string FirstName { get; set; }

    public long? Zipcode { get; set; }

    public string orders { get; set; }

    public long? orderID { get; set; }
}