// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Assignmet_EF_D01.Models;

public partial class dailytrn
{
    public int UserID { get; set; }

    public int? trsnAmount { get; set; }
}